name: 'PR Screenshot'
description: 'Automatically captures screenshots of UI changes in PRs'
author: 'Your Name'
branding:
  icon: 'camera'
  color: 'purple'

inputs:
  url:
    description: 'URL to capture screenshot of'
    required: true
  wait-for-selector:
    description: 'CSS selector to wait for before taking screenshot'
    required: false
    default: 'body'
  viewport-width:
    description: 'Width of viewport for screenshot'
    required: false
    default: '1280'
  viewport-height:
    description: 'Height of viewport for screenshot'
    required: false
    default: '800'
  output-path:
    description: 'Path to save screenshot to'
    required: false
    default: './screenshot.png'
  auth-token:
    description: 'GitHub token for PR comments'
    required: true
    default: ${{ github.token }}
  comment-on-pr:
    description: 'Whether to comment on PR with screenshot'
    required: false
    default: 'true'
  full-page:
    description: 'Whether to capture full page screenshot'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
      
    - name: Run screenshot script
      run: node ${{ github.action_path }}/index.js
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_WAIT-FOR-SELECTOR: ${{ inputs.wait-for-selector }}
        INPUT_VIEWPORT-WIDTH: ${{ inputs.viewport-width }}
        INPUT_VIEWPORT-HEIGHT: ${{ inputs.viewport-height }}
        INPUT_OUTPUT-PATH: ${{ inputs.output-path }}
        INPUT_AUTH-TOKEN: ${{ inputs.auth-token }}
        INPUT_COMMENT-ON-PR: ${{ inputs.comment-on-pr }}
        INPUT_FULL-PAGE: ${{ inputs.full-page }}
        GITHUB_TOKEN: ${{ inputs.auth-token }}